albion/urls.py
from django.urls import path, include
from . import views
#from cards.utils import role_required
from django.conf import settings
from django.conf.urls.static import static

app_name = 'albion'

urlpatterns = [

    path('', views.albion, name='albion'),
]

aliancestroyrb/urls.py
from django.urls import path, include
from . import views
#from cards.utils import role_required
from django.conf import settings
from django.conf.urls.static import static

app_name = 'aliancestroyrb'

urlpatterns = [

    path('', views.scbeton, name='aliancestroyrb'),
]

index/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
]

scbeton/urls.py
from django.urls import path, include
from . import views
#from cards.utils import role_required
from django.conf import settings
from django.conf.urls.static import static

app_name = 'scbeton'

urlpatterns = [

    path('', views.scbeton, name='scbeton'),
]

vitiaz/urls.py
from django.urls import path, include
from . import views
#from cards.utils import role_required
from django.conf import settings
from django.conf.urls.static import static

app_name = 'vitiaz'

urlpatterns = [

    path('', views.vitiaz, name='vitiaz'),
]

web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('albion', include('albion.urls', namespace='albion')),
    path('vitiaz', include('vitiaz.urls', namespace='vitiaz')),
    path('scbeton', include('scbeton.urls', namespace='scbeton')),
    path('aliancestroyrb', include('aliancestroyrb.urls', namespace='aliancestroyrb')),
]

aliancestroyrb/models.py
from django.db import models

# Create your models here.

albion/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponse
import datetime

def albion(request):
    return render(request, 'albion/index.html')

aliancestroyrb/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponse
import datetime

def scbeton(request):
    return render(request, 'aliancestroyrb/index.html')

index/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponse
import datetime

def index(request):
    return render(request, 'index/index.html')

scbeton/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponse
import datetime

def scbeton(request):
    return render(request, 'scbeton/index.html')

vitiaz/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponse
import datetime

def vitiaz(request):
    return render(request, 'vitiaz/index.html')

albion/templates/albion/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Albion</title>

   
    <link href="{% static "albion/css/bootstrap.min.css" %}" rel="stylesheet">

  
    <link href="{% static "albion/css/animate.css" %}" rel="stylesheet">
    <link href="{% static "albion/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">

   
    <link href="{% static "albion/css/style.css" %}" rel="stylesheet">
    <link href="{% static "albion/img/ico/favico.png" rel="shortcut icon" %}" />
    <link href="{% static "albion/img/ico/favico.ico" rel="shortcut icon" %}" />
</head>
<body id="page-top" class="landing-page no-skin-config">
<div class="navbar-wrapper">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="page-scroll" href="#page-top">HOME</a></li>
                        <li><a class="page-scroll" href="#platform">Блоки</a></li>    
                        <li><a class="page-scroll" href="#moduls">Модули</a></li> 
                                                                 
                        <li><a class="page-scroll" href="#contact">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </nav>
</div>
<div id="inSlider" class="carousel carousel-fade" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#inSlider" data-slide-to="0" class="active"></li>
        <li data-target="#inSlider" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Автоматизация никогда <br/> 
						не была<br/>
                        такой простой<br/>
                        </h1>
                    <h1>Все что нужно - <br/> в одной системе</h1>
                </div>
                <div class="carousel-image wow zoomIn">
                    <img src="{% static "albion/img/laptop.png" %}" alt="laptop"/>
                </div>
            </div>
           
            <div class="header-back one"></div>

        </div>
 
    </div>
    <a class="left carousel-control" href="#inSlider" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#inSlider" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>



<section  id= "platform" class="container features">
    <div class="row">
        <div class="col-lg-12 text-center">
            <div class="navy-line"></div>
            <h1>CRM + ERP<br/> <span class="navy">новый подход к реализации проектов</span> </h1>
            
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-3 text-center wow fadeInLeft">
            <div>
                <i class="fa fa-shopping-cart features-icon"></i>
                <h2>Продажи</h2>
                <p>Повышайте эффективность продаж организуя работу продавцов. Увеличивайте выручку.</p>
            </div>
            <div class="m-t-lg">
                <i class="fa  fa-cog features-icon"></i>
                <h2>Управление проектами</h2>
                <p>Планируйте работы, контролируйте задачи. Выполняйте все обазательства точно в срок.</p>
            </div>
            <div class="m-t-lg">
                <i class="fa fa-bar-chart features-icon"></i>
                <h2>Анализ</h2>
                <p>Используйте KPI. Анализируйте информацию.</p>
            </div>
            <div class="m-t-lg">
                <i class="fa fa-compass features-icon"></i>
                <h2>Интернет коммерция</h2>
                <p>Увеличивайте ваши онлайн продажи, продавайте на любых страницах вашего сайта.</p>
            </div>
        </div>
        <div class="col-md-6 text-center wow zoomIn">
            <img src="{% static "albion/assets/img/perspective.png" %}" alt="dashboard" class="img-responsive">
        </div>
        <div class="col-md-3 text-center wow fadeInRight">
            <div>
                <i class="fa fa-random features-icon"></i>
                <h2>Бизнес процессы</h2>
                <p>Управляйте! Повышайте эффективность при помощи настройки бизнес-процессов.</p>
            </div>
            <div class="m-t-lg">
                <i class="fa fa-credit-card features-icon"></i>
                <h2>Лояльность</h2>
                <p>Дружите с клиентами! Запустите свою программу лояльности.</p>
            </div>
            <div class="m-t-lg">
                <i class="fa fa-location-arrow features-icon"></i>
                <h2>Автоматизация лидов</h2>
                <p>Создавайте автоматизированные кампании, уточняйте сегментацию лидов и контролируйте их эффективность.</p>
            </div>
            <div class="m-t-lg">
                <i class="fa fa-wrench features-icon"></i>
                <h2>API</h2>
                <p>Интегрируйте  с  любыми системами.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 text-center">
            <div class="navy-line"></div>
            <h1>Создайте новое будущее Вашей компании</h1>
            <p>Наша цель - улучшение работы компаний, повышение эффективности бизнеса через использование простых, эффективных и недорогих инструментов. Мы предлагаем отличные продукты для решения ваших бизнес-задач.</p>
        </div>
    </div>
    <div class="row features-block">
        <div class="col-lg-6 features-text wow fadeInLeft">
            
            <h2>Предложение</h2>
            <p>Наши решения предназначены для малых и средних коммерчских организаций и компаний, желающих оптимизировать свою работу и повысить эффективность.</p>
            <p>Система имеет модульную архитектуру. Модули системы охватывают все функциональные области деятельности современной  компании, от личного кабинета, CRM и интернет магазина, до торговли, учета склада, производственного учета и планирования, работы с персоналом и так далее. Каждый модуль может работать самостоятельно, как отдельная программа. Все остальные модули гармонично интегрируются, создавая единое целое. Благодаря такому подходу вы можете начать с решения той задачи, которая наиболее актуальна для вас, подключая остальные модули по мере необходимости. Это обеспечивает быстрое внедрение, простое и быстрое развитие вашей информационной системы. Сегодня система насчитывает более 50 различных модулей.</p>
       
        </div>
        
        <div class="col-lg-6 text-right wow fadeInRight">
            <img src="{% static "albion/assets/img/dashboard.png" %}" alt="dashboard" class="img-responsive pull-right">
        </div>
    </div>
</section>

<section id= "moduls" class="features">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>Модули</h1>
                <p>Немножко подробнее</p>
            </div>
        </div>
        <div class="row features-block">
            <div class="col-md-4">
                <h2>Loyalty</h2>
                <p>Обеспечивает автоматизацию всех типов программ лояльности – дисконтных, дисконтно-накопительных, бонусных, дисконтно-бонусных, клубных программ, позволяя работать со всеми аспектами программ лояльности.</p>
				 <br/>
				 <p>Выступает единым процессинговым центром, в который стекается информация обо всех транзакциях, служит общим хранилищем полной информации о клиенте, предоставляет необходимые данные для построения эффективных взаимоотношений с клиентом и формирования его лояльности</p>
           
            </div>
           
            <div class="col-md-4">
                <h2>CRM </h2>
                <p>CRM позволяет вести единую базу клиентов вашей компании, в которой храниться вся информация о клиенте и его взаимоотношениях, а также сегментировать по различным параметрам.</p>
				 <br/>
				 <p>CRM выступает единым конструктором для автоматизации бизнес процесса продажи продуктов вашей компании, прохождения различного уровня сложности стадий процесса продажи до завершения сделки. </p>
            
            </div>
            
            <div class="col-md-4">
                <h2>Bank</h2>
                <p>Отраслевое решения для автоматизации бизнес процессов финансовых организаций: кредитный конвеер, заключение договоров РКО, работа с просроченной задолженностью, выдача банковских карт, электронное хранение документов и т.п.</p>
				 <br/>
				 <p>Автоматизирует деятельность фронт и мидл офисных подразделений Банка, тем самым позволяя ускорить и улучшить процесс обслуживания клиента, обеспечить контроль сроков принятий решений и исключить ошибки при вводе данных.</p>
           
            </div>
        </div>
    </div>

</section>



<section id="contact" class="gray-section contact">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>Наши контакты</h1>
               
            </div>
        </div>
        <div class="row m-b-lg">
            <div class="col-lg-3 col-lg-offset-3">
                <address>
                    <strong><span class="navy">ООО "Альбион"</span></strong><br/>
                    ИНН 0274180605<br/>
                    КПП 027401001<br/>
                    ОГРН 1130280057280
                    <abbr title="Phone">P:</abbr> +7(XXX) ZZZZZZ
                </address>
            </div>
      
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <a href="mailto:torg@al-bion.ru" class="btn btn-primary">Отправьте сообщение</a>
           
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg m-b-lg">
                <p><strong>&copy; 2015 Albion</strong><br/> </p>
            </div>
        </div>
    </div>
</section>

<script src="{% static "albion/js/jquery-2.1.1.js" %}"></script>
<script src="{% static "albion/js/bootstrap.min.js" %}"></script>
<script src="{% static "albion/js/plugins/metisMenu/jquery.metisMenu.js" %}"></script>
<script src="{% static "albion/js/plugins/slimscroll/jquery.slimscroll.min.js" %}"></script>

<script src="{% static "albion/js/inspinia.js" %}"></script>
<script src="{% static "albion/js/plugins/pace/pace.min.js" %}"></script>
<script src="{% static "albion/js/plugins/wow/wow.min.js" %}"></script>


<script>

    $(document).ready(function () {

        $('body').scrollspy({
            target: '.navbar-fixed-top',
            offset: 80
        });

        // Page scrolling feature
        $('a.page-scroll').bind('click', function(event) {
            var link = $(this);
            $('html, body').stop().animate({
                scrollTop: $(link.attr('href')).offset().top - 50
            }, 500);
            event.preventDefault();
        });
    });

    var cbpAnimatedHeader = (function() {
        var docElem = document.documentElement,
                header = document.querySelector( '.navbar-default' ),
                didScroll = false,
                changeHeaderOn = 200;
        function init() {
            window.addEventListener( 'scroll', function( event ) {
                if( !didScroll ) {
                    didScroll = true;
                    setTimeout( scrollPage, 250 );
                }
            }, false );
        }
        function scrollPage() {
            var sy = scrollY();
            if ( sy >= changeHeaderOn ) {
                $(header).addClass('navbar-scroll')
            }
            else {
                $(header).removeClass('navbar-scroll')
            }
            didScroll = false;
        }
        function scrollY() {
            return window.pageYOffset || docElem.scrollTop;
        }
        init();

    })();

    // Activate WOW.js plugin for animation on scrol
    new WOW().init();

</script>

</body>
</html>

aliancestroyrb/templates/aliancestroyrb/index.html
{% load static %}

<!DOCTYPE html>
<html style="font-size: 16px;" lang="ru"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="АЛЬЯНС СТРОЙ">
    <meta name="description" content="">
    <title>АЛЬЯНС СТРОЙ</title>
    <link rel="stylesheet" href="{% static "aliancestroyrb/nicepage.css"%}" media="screen">
<link rel="stylesheet" href="{% static "aliancestroyrb/main.css"%}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static "aliancestroyrb/jquery.js"%}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static "aliancestroyrb/nicepage.js"%}" defer=""></script>
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    
    
    
    
    
    
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": ""
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="Главная">
    <meta property="og:type" content="website">
  <meta data-intl-tel-input-cdn-path="intlTelInput/"></head>
  <body data-home-page="index.html" data-home-page-title="Главная" class="u-body u-xl-mode" data-lang="ru"><header class="u-clearfix u-custom-color-1 u-header u-header" id="sec-5536"><div class="u-clearfix u-sheet u-sheet-1">
        <nav class="u-menu u-menu-one-level u-offcanvas u-menu-1">
          <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px;">
            <a class="u-button-style u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
              <svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
              <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
</g></svg>
            </a>
          </div>
          <div class="u-custom-menu u-nav-container">
            <ul class="u-nav u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="index.html#carousel_fdcf" style="padding: 10px 20px;">Главная</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="index.html#sec-bfbd" style="padding: 10px 20px;">Преимущества</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="index.html#carousel_b8bb" style="padding: 10px 20px;">Контакты</a>
</li></ul>
          </div>
          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-inner-container-layout u-sidenav-overflow">
                <div class="u-menu-close"></div>
                <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="index.html#carousel_fdcf">Главная</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="index.html#sec-bfbd">Преимущества</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="index.html#carousel_b8bb">Контакты</a>
</li></ul>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
        </nav>
      </div></header>
    <section class="u-clearfix u-image u-shading u-section-1" id="carousel_fdcf" data-image-width="6000" data-image-height="4000">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-clearfix u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-container-style u-layout-cell u-left-cell u-size-20 u-layout-cell-1">
                <div class="u-container-layout u-container-layout-1">
                  <h2 class="u-text u-text-default u-text-1">О НАС</h2>
                </div>
              </div>
              <div class="u-container-style u-layout-cell u-size-21 u-layout-cell-2">
                <div class="u-container-layout u-container-layout-2">
                  <h5 class="u-custom-font u-text u-text-font u-text-2">Строительная Компания «Альянс строй» вышла на рынок строительства уже более 10 лет назад. На протяжении этого времени, мы успешно реализовали множество объектов, принимали регулярное участие в выставках и всегда использовали в проектах только новейшие технологии.<br>Множество отзывов&nbsp;от довольных клиентов - лучшее тому подтверждение.
                  </h5>
                </div>
              </div>
              <div class="u-container-style u-layout-cell u-right-cell u-size-19 u-layout-cell-3">
                <div class="u-container-layout u-valign-bottom u-container-layout-3">
                  <h5 class="u-custom-font u-text u-text-font u-text-3"> Наша строительная компания работает только с лучшими, проверенными временем, поставщиками строительных материалов и использует современные технологии в строительстве. Все используемые нами материалы высокого качества.<br>Сотрудники строительной компании - это высококвалифицированные профессионалы с многолетним опытом работы в области строительства. Имеется свой парк спецтехники. Гарантия на все виды работ.&nbsp;
                  </h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="u-clearfix u-custom-color-1 u-section-2" id="sec-00bb">
      <div class="u-clearfix u-sheet u-sheet-1"></div>
    </section>
    <section class="u-clearfix u-grey-5 u-section-3" id="sec-fd2b">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <div class="u-clearfix u-expanded-width u-gutter-10 u-layout-wrap u-layout-wrap-1">
          <div class="u-layout" style="">
            <div class="u-layout-row" style="">
              <div class="u-container-style u-layout-cell u-left-cell u-size-30 u-size-xs-60 u-layout-cell-1" src="">
                <div class="u-container-layout u-container-layout-1">
                  <h2 class="u-text u-text-1">ООО "АЛЬЯНС СТРОЙ </h2>
                  <p class="u-text u-text-2">450005, Башкортостан респ, Уфа г, 50-летия Октября ул, дом 16, офис 10 </p>
                </div>
              </div>
              <div class="u-align-center u-container-style u-image u-layout-cell u-right-cell u-size-30 u-size-xs-60 u-image-1" src="" data-image-width="976" data-image-height="766">
                <div class="u-container-layout u-container-layout-2" src=""></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="u-clearfix u-custom-color-1 u-section-4" id="sec-c71f">
      <div class="u-clearfix u-sheet u-sheet-1"></div>
    </section>
    <section class="u-clearfix u-custom-color-1 u-section-5" id="sec-bfbd">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-clearfix u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-container-style u-image u-layout-cell u-size-30 u-image-1" data-image-width="5184" data-image-height="3456">
                <div class="u-container-layout u-container-layout-1"></div>
              </div>
              <div class="u-container-style u-layout-cell u-size-30 u-layout-cell-2">
                <div class="u-container-layout u-container-layout-2">
                  <h2 class="u-align-center u-custom-font u-text u-text-font u-text-1">НАШИ ПРЕИМУЩЕСТВА </h2>
                  <ul class="u-align-left u-text u-text-default u-text-2">
                    <li> Проекты и цены на любой вкус</li>
                    <li>Качественно реализуем любой проект</li>
                    <li>Разрабатываем индивидуальный проект с учетом ваших потребностей и вкусов</li>
                    <li>Подбираем необходимые стройматериалы</li>
                    <li>Работаем в соответствии с общестроительными нормами и стандартами</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="u-clearfix u-custom-color-1 u-section-6" id="carousel_f826">
      <div class="u-clearfix u-sheet u-sheet-1"></div>
    </section>
    <section class="u-clearfix u-custom-color-1 u-section-7" id="carousel_b8bb">
      <div class="u-clearfix u-sheet u-sheet-1"></div>
    </section>
    
    
    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-5050"><div class="u-clearfix u-sheet u-sheet-1">
        <h5 class="u-align-left u-custom-font u-text u-text-font u-text-1">
          <span style="font-weight: 700;">Контакты</span>
          <br>
          <br>Телефон: 8-ХХХ-ХХХ-ХХ-ХХ<br>E-mail: agent@gmail.com
        </h5>
      </div></footer>

  
</body></html>

index/templates/index/index.html
{% load staticfiles %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
        <script src="https://use.fontawesome.com/2cd42b3a14.js"></script>

        <!-- Latest compiled and minified CSS  -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>




    </head>
    <body>

            <nav class="navbar navbar-expand-lg navbar-dark bg-secondary" >
                <a class="navbar-brand" href="{% url 'index:index' %}">Сайты</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Список
                                </a>
                                <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="{% url 'albion:albion' %}">Альбион</a>
                                    <a class="dropdown-item" href="{% url 'vitiaz:vitiaz' %}">Витязь</a>
                                    <a class="dropdown-item" href="{% url 'scbeton:scbeton' %}">Спецбетон</a>
                                    <a class="dropdown-item" href="{% url 'aliancestroyrb:aliancestroyrb' %}">АЛЬЯНС СТРОЙ</a>
                                </div>
                            </li>


                        </ul>
                    </div>

                </nav>

            {# Display django.contrib.messages as Bootstrap alerts #}
            {% bootstrap_messages %}



            <main role="main">

                <div class="container">

                  {% block content %}{% endblock %}

                </div>

            </main>

        </body>
</html>